jump_line = "\n-----------------------------------------------------"

cr_acra = "tpl.crashreporting.acra"
cr_crashlytics = "tpl.crashreporting.crashlytics"
cr_newrelic = "tpl.crashreporting.newrelic"
cr_template = "tpl.crashreporting.template"
ads_max = "tpl.ads.banner.max"
ads_chartboost = "tpl.ads.banner.chartboost"
ads_admob = "tpl.ads.banner.admob"
ads_template = "tpl.ads.banner.template"
moni_newrelic = "tpl.monitoring.newrelic"
moni_amplitude = "tpl.monitoring.amplitude"
moni_firebase = "tpl.monitoring.firebase"
moni_template = "tpl.monitoring.template"
